languages:
   Ruby: true
engines:
   duplication:
      enabled: true
      config:
         languages: 
            ruby:
               mass_threshold: 40
exclude_paths:
- bin/**/*
- db/**/*
- lib/**/*
- script/**/*
- spec/**/*
- tmp/**/*
- Gemfile
- Gemfile.lock
- public/**/*
- features/**/*
